meta_product_name: "Busque"
meta_title: "Busque - Sistema de Cadastro de Passageiros"
meta_description: "Sistema usado pela Polícia Rodoviária Federal para melhoria do sistema de abordagem de coletivos"
meta_image: "Logo-BUSque.png" # should exist in `app/assets/images/`